# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RiversideOrthopaedics

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d41914d072e94cd780d6fbcfa0621bd5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_104073d5079a4ef48744637aa354cd50 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d41914d072e94cd780d6fbcfa0621bd5 }}/jimmylagattuta/orthoriverside-web-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RiversideOrthopaedics'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f7abdfca0d54422ebf386e403887d3be }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d41914d072e94cd780d6fbcfa0621bd5 }}/jimmylagattuta/orthoriverside-web-app:${{ github.sha }}'